export let products = [
  {
    id: 1,
    title: "Tazón y Platito Verbena",
    price: "$ 12.500",
    img: "https://res.cloudinary.com/dbo7c3awi/image/upload/v1718601823/taza_wnxbaj.jpg",
    category: "Vajilla",
  },
  {
    id: 2,
    title: "Plato Ficus por unidad",
    price: "$ 7.000",
    img: "https://res.cloudinary.com/dbo7c3awi/image/upload/v1718601823/plato_imlm56.jpg",
    category: "Vajilla",
  },
  {
    id: 3,
    title: "Bowl Loto",
    price: "$ 6.000",
    img: "https://res.cloudinary.com/dbo7c3awi/image/upload/v1718601823/bowl_hzk30h.jpg",
    category: "Vajilla",
  },
  {
    id: 4,
    title: "Florero Monstera",
    price: "$ 5.000",
    img: "https://res.cloudinary.com/dbo7c3awi/image/upload/v1718601823/florero_nfhwxs.jpg",
    category: "Decoración",
  },
  {
    id: 5,
    title: "Maceta Calathea",
    price: "$ 14.000",
    img: "https://res.cloudinary.com/dbo7c3awi/image/upload/v1718601823/maceta_ayqzok.jpg",
    category: "Decoración",
  },
  {
    id: 6,
    title: "Jarra Acasia",
    price: "$ 10.500",
    img: "https://res.cloudinary.com/dbo7c3awi/image/upload/v1718601823/jarra_gwve0m.jpg",
    category: "Vajilla",
  },
  {
    id: 7,
    title: "Porta Cuchara Peruviana",
    price: "$ 5.500",
    img: "https://res.cloudinary.com/dbo7c3awi/image/upload/v1718601823/apoya_cuchara_wcjyji.jpg",
    category: "Decoración",
  },
  {
    id: 8,
    title: "Alhajero Cactus",
    price: "$ 5.500",
    img: "https://res.cloudinary.com/dbo7c3awi/image/upload/v1718601823/alhajero_ngn5m8.jpg",
    category: "Decoración",
  },
];
