export let products = [
  {
    id: 1,
    title: "Tazón y Platito Verbena",
    price: 12500,
    img: "https://res.cloudinary.com/dbo7c3awi/image/upload/v1718601823/taza_wnxbaj.jpg",
    category: "Vajilla",
    stock: 5,
  },
  {
    id: 2,
    title: "Plato Ficus",
    price: 7000,
    img: "https://res.cloudinary.com/dbo7c3awi/image/upload/v1718601823/plato_imlm56.jpg",
    category: "Vajilla",
    stock: 10,
  },
  {
    id: 3,
    title: "Bowl Loto",
    price: 6000,
    img: "https://res.cloudinary.com/dbo7c3awi/image/upload/v1718601823/bowl_hzk30h.jpg",
    category: "Vajilla",
    stock: 10,
  },
  {
    id: 4,
    title: "Florero Monstera",
    price: 5000,
    img: "https://res.cloudinary.com/dbo7c3awi/image/upload/v1718601823/florero_nfhwxs.jpg",
    category: "Decoración",
    stock: 6,
  },
  {
    id: 5,
    title: "Maceta Calathea",
    price: 14000,
    img: "https://res.cloudinary.com/dbo7c3awi/image/upload/v1718601823/maceta_ayqzok.jpg",
    category: "Decoración",
    stock: 8,
  },
  {
    id: 6,
    title: "Jarra Acasia",
    price: 10000,
    img: "https://res.cloudinary.com/dbo7c3awi/image/upload/v1718601823/jarra_gwve0m.jpg",
    category: "Vajilla",
    stock: 4,
  },
  {
    id: 7,
    title: "Porta Cuchara Peruviana",
    price: 5000,
    img: "https://res.cloudinary.com/dbo7c3awi/image/upload/v1718601823/apoya_cuchara_wcjyji.jpg",
    category: "Decoración",
    stock: 20,
  },
  {
    id: 8,
    title: "Alhajero Cactus",
    price: 5500,
    img: "https://res.cloudinary.com/dbo7c3awi/image/upload/v1718601823/alhajero_ngn5m8.jpg",
    category: "Decoración",
    stock: 5,
  },
];
